trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'sdk/dotnet/*'
      - '.ci/*'
    exclude:
      - .github/*
      - .vscode/*
      - docs/*
      - samples/*
      - .gitignore
      - CODE_OF_CONDUCT.md
      - LICENSE.txt
      - README.md
      - SECURITY.md
      - SUPPORT.md

pool:
  vmImage: 'windows-latest'

variables:
  group: internal-feed-variables
  netSdkPath: 'sdk/dotnet'
  solution: '$(netSdkPath)/Datasync.Framework.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- script: echo 'FeedName'
- script: echo $(VstsFeedName)
- script: echo 'netSdkPath'
- script: echo $(netSdkPath)
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration)'
    projects: '$(solution)'

- task: DotNetCoreCLI@2
  displayName: 'dotnet test'
  inputs:
    command: 'test'
    arguments: '--configuration $(buildConfiguration)'
    projects: '$(netSdkPath)/test/*Datasync*/*.csproj'

- task: NuGetCommand@2
  displayName: 'nuget push'
  inputs:
    command: 'push'
    feedsToUse: 'select'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '$(VstsFeedName)'
    versioningScheme: 'off'
    allowPackageConflicts: true
