trigger:
  branches:
    include:
      - main
  paths:
    include:
      - 'sdk/dotnet/*'
      - '.ci/*'
    exclude:
      - .github/*
      - .vscode/*
      - docs/*
      - samples/*
      - .gitignore
      - CODE_OF_CONDUCT.md
      - LICENSE.txt
      - README.md
      - SECURITY.md
      - SUPPORT.md

name: $(date:yy.Mdd)$(rev:.r)

pool:
  vmImage: 'windows-latest'

variables:
- group: internal-feed-variables
- name: netSdkPath
  value: 'sdk/dotnet'
- name: solution
  value: '$(netSdkPath)/Datasync.Framework.sln'
- name: buildPlatform
  value: 'Any CPU'
- name: buildConfiguration
  value: 'Release'
- name: dotnetVersion
  value: '6.0.x'
- name: buildVersion
  value: '$(Build.BuildNumber)'
  
steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet build'
  inputs:
    command: 'build'
    arguments: '--configuration $(buildConfiguration) /p:Version=$(Build.BuildNumber) /p:PackageVersion=$(buildVersion)'
    projects: '$(solution)'
    version: $(dotnetVersion)

- task: DotNetCoreCLI@2
  displayName: "dotnet pack"
  inputs:
    command: 'pack'
    arguments: '--configuration $(buildConfiguration)'
    packagesToPack: '$(solution)'
    nobuild: true
    version: $(dotnetVersion)
    versioningScheme: byEnvVar
    versionEnvVar: buildVersion 
    
- task: NuGetCommand@2
  displayName: 'nuget push'
  inputs:
    command: 'push'
    feedsToUse: 'select'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'internal'
    publishVstsFeed: '$(VstsFeedName)'
    versioningScheme: 'off'
    allowPackageConflicts: true
